apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: micro-services
images:
- name: build-app-flask
  newName: silvadiego23/app-flask
  newTag: 5d74a8981cdb11edbb51bc2e180e38ffd21aab64
- name: silvadiego23/app-flask
  newTag: 21e995f75b4f29e8ac65e07bd686c46bcdf5882a
