apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
namespace: micro-services
images:
  - name: build-app-flask
    newName: silvadiego23/app-flask
    newTag: latest