name: Build image

on:
  push: 
    branches: [ master ]

env:
  DOCKERHUB_USER: silvadiego23
  APP_NAME: app-flask

jobs:
  setup-build-publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login Dockerhub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push
          uses: docker/build-push-action@v4
          with:
           context: .
           push: true
           tags: ${{ env.DOCKERHUB_USER}}/${{ env.APP_NAME }}:${{ github.sha }}

  deployment-image:
      name: Deploy
      runs-on: ubuntu-latest
      needs: setup-build-publish
      steps:
        - name: Checkout
          uses: actions/checkout@v4
       
        - name: Install kustomize and generate new file
          uses: imranismail/setup-kustomize@v2
        - run: |
            cd k8s
            kustomize edit set image ${{ env.DOCKERHUB_USER}}/${{ env.APP_NAME }}:${{ github.sha }}
            git commit -am "Generate new tag image `${GITHUB_SHA}`"
            git push
